---
apiVersion: v1
kind: Service
metadata:
  name: sqs-service
spec:
  clusterIP: 10.98.54.124
  selector:
    app: sqs-pod 
  ports:
  - port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-deployment
  labels:
    app: sqs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sqs-pod
  template:
    metadata:
      labels:
        app: sqs-pod
    spec:
      dnsPolicy: Default
      containers:
      - name: sustain-query-server 
        image: sustain/sustain-query-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sqs-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sqs-pod
              topologyKey: kubernetes.io/hostname
            weight: 100
