---
apiVersion: v1
kind: Service
metadata:
  name: sqs-service
spec:
  clusterIP: 10.98.54.124
  selector:
    app: sqs-pod
  ports:
  - port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-deployment
  labels:
    app: sqs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sqs-pod
  template:
    metadata:
      labels:
        app: sqs-pod
    spec:
      dnsPolicy: Default
      containers:
      - name: sustain-query-server 
        image: sustain/sustain-query-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051 # SQS gRPC Service
        - containerPort: 50052 # Spark Driver Port
        - containerPort: 50053 # Spark Driver BlockManager Port
        - containerPort: 4040  # Spark Driver UI Port
        - containerPort: 9079  # Default Executor Port
        env:
          - name: NODE_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_ENV # Tells SQS it is running in a K8s Pod
            value: "true"
          - name: SERVER_PORT
            value: "50051"
          - name: DB_NAME
            value: "sustaindb"
          - name: DB_HOST
            value: "localhost"
          - name: DB_PORT
            value: "27018"
          - name: SPARK_DRIVER_PORT
            value: "50052"
          - name: SPARK_DRIVER_BLOCKMANAGER_PORT
            value: "50053"
          - name: SPARK_DRIVER_UI_PORT
            value: "4040"
          - name: SPARK_DEFAULT_EXECUTOR_PORT
            value: "9079"
          - name: SPARK_MASTER
            value: "spark://lattice-100.cs.colostate.edu:8079"
          - name: SPARK_DRIVER_PORT
            value: "50052"
          - name: SPARK_THREAD_COUNT
            value: "4"
          - name: SPARK_EXECUTOR_CORES
            value: "5"
          - name: SPARK_EXECUTOR_CORES
            value: "5"
          - name: SPARK_EXECUTOR_MEMORY
            value: "8G"
          - name: SPARK_INITIAL_EXECUTORS
            value: "5"
          - name: SPARK_MIN_EXECUTORS
            value: "1"
          - name: SPARK_MAX_EXECUTORS
            value: "10"
          - name: SPARK_BACKLOG_TIMEOUT
            value: "10s"
          - name: SPARK_IDLE_TIMEOUT
            value: "10s"
      - name: mongos-router
        image: mongo:4.4.4
        imagePullPolicy: Always
        command: ['sh', '-c', 'mongos --configdb cfgrs/lattice-147:27017,lattice-148:27017,lattice-149:27017 --bind_ip_all --port 27018']
        ports:
          - containerPort: 27018
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sqs-node
                operator: In
                values:
                - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sqs-pod
              topologyKey: kubernetes.io/hostname
            weight: 100
